@startuml uses_cases_controle

left to right direction


actor Admin as admin

package controle {

  Admin -->  (Cas d'utilisation) 
  (extend 1 Cas d'utilisation)  <..  (Cas d'utilisation)  : <<extend>>
  (extend 2 Cas d'utilisation)  <.  (Cas d'utilisation)  : <<extend>>
}  

' note right of admin : "note 1"

@enduml