classDiagram

direction RL

namespace gestion_rh{
class Apprenant
class Formateur 
class  Groupe 

}
Groupe "1" --> "*" Apprenant
Formateur "*" --> "1" Groupe

namespace gestion_competences {
class NiveauCompetence
class Competence
class Technologie 
}
Competence "*" -- "*" Technologie


note for  StatutTache "Le statut de projet est calculable à partir les status de ces tâches"

namespace pk_projets {


  class Projet {
    id: int
    nom: string
    description: string
    objectifs: string
    dateDebut: date
    dateEcheance: date
  }

  class Tache {
    id: int
    nom: string
    description: string
    priorité: string
    dateÉchéance: date
  }

  class StatutTache{
    id: int
    nom: string
    description: string
  }

  class Equipe {
    id: int
    nom: String
    description: String
  }

}




Formateur "1" --> "*" Projet : "Crée plusieurs de projets"

Projet "1" --> "*" Tache
Projet "*" --> "*" Competence : "En relation avec plusieurs technoligies"

Tache "*" --> "1" Apprenant : "affectation à un seul apprenant"



Tache "*" --> "1" NiveauCompetence
Tache "*" --> "*" Technologie
Tache "*" --> "1" StatutTache 


 
Equipe "*" --> "1" Projet
Equipe   "*" --> "*"  Apprenant : "participants"