classDiagram

namespace pkg_notifications {

class NotificationRepository {
  AjouterNotificationParApprenant(apprenant_id)
  AjouterNotificationParEquipe(equipe_id)
  AjouterNotificationParGroupe(groupe_id)
}
}