@startuml uses_cases_pkg_realisation_projet

left to right direction

actor Apprenant as apprenant
actor Formateur as formateur

package pkg_realisation_projet {

 apprenant -- (Gestion des livrables)
 formateur -- (Gestion catégories des livrables)
 formateur -- (Gestion des message)
 (Gestion des message) <. (Rédaction des message d'un projet)
 (Gestion des message) <. (Rédaction des message d'une tâche)

}  

package pkg_projets{

  (Modifier projet)  <.. (Rédaction des message d'un projet)
  (Modifier tâche)  <.. (Rédaction des message d'une tâche)
  (Modifier tâche)  <.. (valider la tâche)

}


' note right of admin : "note 1"

@enduml