classDiagram

namespace gestion_competences {
class Competence {
  id : int
  nom : String
  description : String
}
class NiveauCompetence {
  id : int
  nom : String
  description : String
}
class Technologie {
  id : int
  nom : String
  description : String
}

class CategorieTechnologie {
  id : int
  nom : String
  description : String
}
}

Competence "*" --> "1" NiveauCompetence
Competence "1" --> "*" Technologie 
Technologie "*" --> "1" CategorieTechnologie