classDiagram
class Technologie {
  id : int
  nom : String
  description : String
}
class CategorieTechnologie {
  id : int
  nom : String
  description : String
}
Technologie "*" --> "1" CategorieTechnologie